version: "3.9"
services:
  api:
    image: 1espoirhenri/dispatch-monitoring:1.0.1
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports: ["8000:8000"]
    volumes:
      - ./:/app
      - ./feedback_frames:/app/feedback_frames
    shm_size: "1gb"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]   # nếu dùng NVIDIA runtime
  retrain:
    build: .
    command: python retrain/nightly_retrain.py
    volumes: [".:/code"]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
